apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: learning
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-selector
  template:
    metadata:
      labels:
        app: nginx-selector
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
        - name: mysql
          image: mysql:latest

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: learning
spec:
  type: NodePort
  selector:
    app: nginx-selector
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80