apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: learning
  labels:
    app: nginx-selector
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: learning
spec:
  type: NodePort
  selector:
    app: nginx-selector
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
