apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: {{ .Values.ns }}
spec:
  type: NodePort
  selector:
    app: nginx-selector
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80